In [1]:
#Q1. List any five functions of the pandas library with execution.

In [2]:
#answer1-
import pandas as pd

In [3]:
#read_csv(): """This function is used to read a CSV file and create a DataFrame from it."""
df = pd.read_csv("services.csv")
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [4]:
#2-dtypes:To show types of data of all columns.
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [5]:
#3-Categorical: To show distinct categories
pd.Categorical(df["location_id"])

[1, 2, 3, 4, 5, ..., 19, 20, 21, 22, 22]
Length: 23
Categories (22, int64): [1, 2, 3, 4, ..., 19, 20, 21, 22]

In [6]:
#4- iloc: it is used for slicing by inbuilt index
df.iloc[0:3]

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [7]:
#5.loc: It is used for slicing by column name
df.loc[0:3,["location_id","program_id","accepted_payments","alternate_name"]]

   location_id  program_id accepted_payments alternate_name
0            1         NaN               NaN            NaN
1            2         NaN               NaN            NaN
2            3         NaN               NaN            NaN
3            4         NaN               NaN            NaN

In [8]:
#Q2. Given a Pandas DataFrame df with columns 'A', 'B', and 'C', write a Python function to re-index the DataFrame with a new index that starts from 1 and increments by 2 for each row.

In [9]:
#answer2- 
def py_func(df):
    df.index = range(1,2*len(df)+1,2)
    return df

In [13]:
df = pd.DataFrame({"A":[1,2,3],"B" :[4,5,6],"C":[6,8,9]})
reindex = py_func(df)
print(reindex)

   A  B  C
1  1  4  6
3  2  5  8
5  3  6  9

In [14]:
#Q3. You have a Pandas DataFrame df with a column named 'Values'. Write a Python function that iterates over the DataFrame and calculates the sum of the first three values in the 'Values' column. The function should print the sum to the console. For example, if the 'Values' column of df contains the values [10, 20, 30, 40, 50], your function should calculate and print the sum of the first three values, which is 60.

In [16]:
#answer3-
def sum_of_first_threedata(df):
    values_column = df['Values']
    sum_values = sum(values_column[:3])
    print("Sum of the first three values:", sum_values)

df = pd.DataFrame({'Values': [10, 20, 30, 40, 50]})
sum_of_first_threedata(df)

Sum of the first three values: 60

In [17]:
#Q4. Given a Pandas DataFrame df with a column 'Text', write a Python function to create a new column 'Word_Count' that contains the number of words in each row of the 'Text' column.

In [22]:
#answer4-
def pw_data(df):
    df["Word_Count"] = df["Text"].str.split().apply(len)

df = pd.DataFrame({"Text": ["My name is mohan","age is 23","add is bhopal"]})
pw_data(df)
print(df)

               Text  Word_Count
0  My name is mohan           4
1         age is 23           3
2     add is bhopal           3

In [23]:
#Q5. How are DataFrame.size() and DataFrame.shape() different?

In [25]:
#answer5-
#DataFrame.size()-
"""It returns the total number of elements in the DataFrame. It is the product of the number of rows
and the number of columns."""
#DataFrame.shape()-
""" It returns a tuple representing the dimensions of the DataFrame, i.e., the number of rows and columns."""
#for example-
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C": [7, 8, 9]})
print(df.size)    
print(df.shape)

9
(3, 3)

In [26]:
#Q6. Which function of pandas do we use to read an excel file?

In [28]:
df=pd.read_excel('LUSID Excel - Setting up your market data.xlsx')

In [ ]:
#Q7.
"""You have a Pandas DataFrame df that contains a column named 'Email' that contains email 
addresses in the format 'username@domain.com'. Write a Python function that creates a new column 
'Username' in df that contains only the username part of each email address.

The username is the part of the email address that appears before the '@' symbol. For example, if the 
email address is 'john.doe@example.com', the 'Username' column should contain 'john.doe'. Your 
function should extract the username from each email address and store it in the new 'Username' 
column"""

In [30]:
def extract_username(df):
    df['Username'] = df["Email"].str.split("@").str[0]

df = pd.DataFrame({"Email": ["john.doe@example.com", "jane.smith@example.com", "johnson@example.com"]})
extract_username(df)
print(df)

                    Email    Username
0    john.doe@example.com    john.doe
1  jane.smith@example.com  jane.smith
2     johnson@example.com     johnson

In [ ]:
#Q8.
"""You have a Pandas DataFrame df with columns 'A', 'B', and 'C'. Write a Python function that selects 
all rows where the value in column 'A' is greater than 5 and the value in column 'B' is less than 10. The 
function should return a new DataFrame that contains only the selected rows.

For example, if df contains the following values:

   A   B   C

0  3   5   1

1  8   2   7

2  6   9   4

3  2   3   5

4  9   1   2
Assignment
Data Science Masters
Your function should select the following rows:   A   B   C

1  8   2   7

4  9   1   2

The function should return a new DataFrame that contains only the selected rows."""

In [31]:
#answer8-
def select_rows(df):
    selected_rows = df[(df["A"] > 5) & (df["B"] < 10)]
    return selected_rows

df = pd.DataFrame({"A": [3, 8, 6, 2, 9], "B": [5, 2, 9, 3, 1], "C": [1, 7, 4, 5, 2]})
selected_df = select_rows(df)
print(selected_df)

   A  B  C
1  8  2  7
2  6  9  4
4  9  1  2

In [32]:
#Q9. Given a Pandas DataFrame df with a column 'Values', write a Python function to calculate the mean, median, and standard deviation of the values in the 'Values' column.

In [34]:
#answer9-
df = pd.DataFrame({"Values": [10, 20, 30, 40, 50]})
Mean = df.mean()
Median = df.median()
Std = df.std()
print("Mean = ",Mean)
print("Median = ",Median)
print("Standard Deviation = ",Std)

Mean =  Values    30.0
dtype: float64
Median =  Values    30.0
dtype: float64
Standard Deviation =  Values    15.811388
dtype: float64

In [35]:
#Q10. Given a Pandas DataFrame df with a column 'Sales' and a column 'Date', write a Python function to create a new column 'MovingAverage' that contains the moving average of the sales for the past 7 days for each row in the DataFrame. The moving average should be calculated using a window of size 7 and should include the current day.

In [37]:
#answer10-
df = pd.DataFrame({"Sales": [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]})
df["MovingAverage"] = df["Sales"].rolling(window=7, min_periods=1).mean()
df

   Sales  MovingAverage
0     10           10.0
1     20           15.0
2     30           20.0
3     40           25.0
4     50           30.0
5     60           35.0
6     70           40.0
7     80           50.0
8     90           60.0
9    100           70.0

In [ ]:
#Q11. 
"""

You have a Pandas DataFrame df with a column 'Date'. Write a Python function that creates a new 
column 'Weekday' in the DataFrame. The 'Weekday' column should contain the weekday name (e.g. 
Monday, Tuesday) corresponding to each date in the 'Date' column.

For example, if df contains the following values:

         Date

0  2023-01-01

1  2023-01-02

2  2023-01-03

3  2023-01-04

4  2023-01-05

Your function should create the following DataFrame:


         Date    Weekday

0  2023-01-01    Sunday

1  2023-01-02     Monday

2  2023-01-03    Tuesday

3  2023-01-04    Wednesday

4  2023-01-05    Thursday

The function should return the modified DataFrame

"""

In [39]:
#answer11-
df = pd.DataFrame({"Date": ["2023-01-01", "2023-01-02", "2023-01-03", "2023-01-04", "2023-01-05"]})
df["Weekday"] = pd.to_datetime(df["Date"]).dt.day_name()
df

         Date    Weekday
0  2023-01-01     Sunday
1  2023-01-02     Monday
2  2023-01-03    Tuesday
3  2023-01-04  Wednesday
4  2023-01-05   Thursday

In [40]:
#Q12. Given a Pandas DataFrame df with a column 'Date' that contains timestamps, write a Python function to select all rows where the date is between '2023-01-01' and '2023-01-31'.

In [42]:
#answer12-
df = pd.DataFrame({"Date": ["2023-01-01", "2023-01-15", "2023-01-31", "2023-02-10"]})
df1 =  df[(df["Date"] >= "2023-01-01") & (df["Date"] <= "2023-01-31")]
df1

         Date
0  2023-01-01
1  2023-01-15
2  2023-01-31

In [43]:
#Q13. To use the basic functions of pandas, what is the first and foremost necessary library that needs to be imported?

In [44]:
"""The first and foremost necessary library that needs to be imported to use the basic functions of pandas is pandas itself(import pandas as pd). 
The pandas library provides data structures and data analysis tools, including the DataFrame and Series objects, as well as 
various functions for data manipulation and analysis. By importing pandas, you gain access to these basic functions and 
can start working with data using pandas"""

'The first and foremost necessary library that needs to be imported to use the basic functions of pandas is pandas itself(import pandas as pd). \nThe pandas library provides data structures and data analysis tools, including the DataFrame and Series objects, as well as \nvarious functions for data manipulation and analysis. By importing pandas, you gain access to these basic functions and \ncan start working with data using pandas'